# Generated by Django 4.1 on 2022-09-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
